name: xiaomi_scale_example
description: Demonstrates how to use the xiaomi_scale plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter
  permission_handler: ^5.0.1+1
  xiaomi_scale:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
